version: "3.7"

services:
  nginx:
    image: nginx:stable-alpine
    container_name: prueba_nginx
    restart: unless-stopped
    tty: true
    user: root
    deploy:
      resources:
        limits:
          memory: 3250M
        reservations:
          memory: 500M
    ports:
      - 8000:80
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - test
    networks:
      - prueba_network

  mysql:
      image: mysql:5.7
      container_name: test_mysql
      restart: unless-stopped
      ulimits:
          nproc: 65535
          nofile:
              soft: 20000
              hard: 40000
      environment:
          MYSQL_DATABASE: laravel_test
          MYSQL_ROOT_PASSWORD: rtmk
      ports:
          - 3307:3306
      volumes:
          - test_data:/var/lib/mysql
      networks:
          - prueba_network

  mailtrap:
      image: 'eaudeweb/mailtrap'
      ports:
          - "8081:80"
  test:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: prueba-mail
    working_dir: /var/www/html
    restart: unless-stopped
    volumes:
      - .:/var/www/html
      - ./public:/var/www/html
    networks:
      - prueba_network

networks:
  prueba_network:

volumes:
  test_data:
